name: studymatcherf
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.1
  flutter:
    sdk: flutter
  line_awesome_flutter: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.10
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    # Add assets from the images directory to the application.
    - lib/images/google.png
    - lib/icons/add_group.png
    - lib/icons/add_group1.png
    - lib/icons/group.png
    - lib/icons/background.png
    - lib/icons/logo.png

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
